import Player from './modules/Player';

const ai = new Player(true);
const player = new Player(false);
console.log(ai.placeShips());
player.placeShips();
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
ai.sendAttack(player);
console.log(player.board);
